listen_addresses = '*'
lc_messages = 'en_US.UTF-8'
lc_monetary = 'en_US.UTF-8'
lc_numeric = 'en_US.UTF-8'
lc_time = 'en_US.UTF-8'
shared_preload_libraries = 'timescaledb'
shared_buffers = 5000MB
effective_cache_size = 15001MB
maintenance_work_mem = 2047MB
work_mem = 2327kB
timescaledb.max_background_workers = 16
max_worker_processes = 41
max_parallel_workers_per_gather = 11
max_parallel_workers = 22
wal_buffers = 16MB
min_wal_size = 512MB
max_wal_size = 1GB
default_statistics_target = 100
random_page_cost = 1.1
checkpoint_completion_target = 0.9
max_connections = 100
max_locks_per_transaction = 512
autovacuum_max_workers = 10
autovacuum_naptime = 10
default_toast_compression = lz4
jit = off
effective_io_concurrency = 256
timescaledb.last_tuned = '2026-02-23T18:40:08Z'
timescaledb.last_tuned_version = '0.18.1'
