#!/usr/bin/env bash
set -e

composer install
bun install

if [ "$1" != "" ]; then
    exec "$@"
else
    php artisan optimize
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
