name: Deploy

concurrency: production

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-complete]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    env:
      GOONHUB_DOCKER_PATH: ${{ secrets.GOONHUB_DOCKER_PATH }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.GOONHUB_DOCKER_PATH }}

    steps:
      - name: Pull image
        run: docker compose pull -q
      - name: Clear old env
        run: echo "" > .env
      - name: Create new shared volume
        run: |
          PUBLIC_VOLUME="goonhub-public-$EPOCHSECONDS"
          echo "PUBLIC_VOLUME=$PUBLIC_VOLUME" >> .env
          docker volume create "$PUBLIC_VOLUME" --label "for=goonhub"
      - name: Create new shared network
        run: |
          WEBBRIDGE_NETWORK="goonhub-webbridge-$EPOCHSECONDS"
          echo "WEBBRIDGE_NETWORK=$WEBBRIDGE_NETWORK" >> .env
          docker network create "$WEBBRIDGE_NETWORK" --label "for=goonhub"
      - name: Rollout new containers
        run: |
          (\
            trap 'kill 0' SIGINT; \
            docker rollout app --wait-after-healthy 5 --pre-stop-hook " \
              touch /tmp/drain && \
              supervisorctl stop scheduler:* && \
              supervisorctl stop pulse:* && \
              sleep 45 \
            " & \
            docker rollout nginx --wait-after-healthy 5 --pre-stop-hook "touch /tmp/drain && sleep 45" & \
            wait\
          )
      - name: Clean up
        run: |
          docker volume prune --filter "label=for=goonhub" -a -f
          docker network prune --filter "label=for=goonhub" -f
