name: Rust-G

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Rust-G Release Tag
        type: string
      branch:
        description: Rust-G Branch
        type: string
  repository_dispatch:
    types: [rustg_release]

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "RUSTG_GIT_REF=${{ inputs.tag != '' && format('refs/tags/{0}', inputs.tag) || format('refs/heads/{0}', inputs.branch) }}" >> "$GITHUB_ENV"
          echo "RUSTG_GIT_REF_NAME=${{ inputs.tag != '' && inputs.tag || inputs.branch }}" >> "$GITHUB_ENV"

      - if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "RUSTG_GIT_REF=${{ github.event.client_payload.ref }}" >> "$GITHUB_ENV"
          echo "RUSTG_GIT_REF_NAME=${{ github.event.client_payload.ref_name }}" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
        with:
          repository: goonstation/rust-g
          ref: ${{ env.RUSTG_GIT_REF }}

      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install zip libgcc-s1:i386 g++-multilib zlib1g-dev:i386

      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: i686-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --target i686-unknown-linux-gnu --release --features all
        env:
          PKG_CONFIG_ALLOW_CROSS: 1

      - run: |
          cd target/i686-unknown-linux-gnu/release
          zip rustg-${{ env.RUSTG_GIT_REF_NAME }}.zip librust_g.so

      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.RUSTG_RELEASES_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.RUSTG_RELEASES_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.RUSTG_RELEASES_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.RUSTG_RELEASES_BUCKET }}
          source-dir: './target/i686-unknown-linux-gnu/release/rustg-${{ env.RUSTG_GIT_REF_NAME }}.zip'
          destination-dir: ./
          keep-file-fresh: true
